### ISSUE TITLE
Move update status functions to be model methods instead

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/eta-notifications-flask#1]
The `update_order_status` and `update_notification_status` functions in views.py both modify a single order. Let's make them methods on the `Order` model instead.

For example, this:

```
def update_notification_status(status, order):
    order.notification_status = status
    db.session.commit()
```

Could probably just be added to the `Order` model like this:

```
def update_notification_status(self, status):
    order.notification_status = status
    db.session.commit()
```

And then referenced in the views as `order.update_notification_status([status])`

**Comment by mcelicalderon** [comment]
@atbaker I removed unnecessary complexity in this endpoint, I have only one now to update notification status. I update the status without a method, just change the model's property and commit the changes in the view

**Comment by atbaker** [comment]
That works - thanks!
