### ISSUE TITLE
README tweaks

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/eta-notifications-flask#2]
I think the README overall looks good. We should tweak a couple things though:
1. Let's add a new step between 5 and 6 that's called "Edit seed data." I accidentally ran the `dbseed` command before I read that the README recommends editing that data before I run the command.
2. Let's add a new step to the end of the README that recommends using ngrok to expose your app to the web. You might want to link to the most recent Twilio blog post on ngrok as part of your instructions:

https://www.twilio.com/blog/2015/09/6-awesome-reasons-to-use-ngrok-when-testing-webhooks.html

**Comment by mcelicalderon** [comment]
done
