### ISSUE TITLE
Remove models package

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/eta-notifications-flask#4]
Since we just have one model, it's fine to have one `models.py` file in the `eta_notifications_flask` directory instead of a `models` package with an `order` module.

Removing the `models` directory and instead putting `Order` inside one `models.py` should make the source code hierarchy a little simpler.

**Comment by mcelicalderon** [comment]
@atbaker let me know if this is what you meant https://github.com/TwilioDevEd/eta-notifications-flask/commit/238459b0912b5760f29edc3e7d81527a0a6367ec

**Comment by atbaker** [comment]
Yup! That's exactly what I meant.
